### ISSUE TITLE
White spaces removed after <span>, <a>, <b>, etc

### ISSUE THREAD

**Issue by dalescher** [xfenix/django-hmin#4]
Thank you for this middleware. It's working better than django-htmlmin regarding per-view caching. However, the minifed code removes the white spaces after some tags (`<span>, <a>, <b>, etc.`). 
Is there a way to do it in a more clever way so we do not need to hardcode `&nbsp;` each time we use such tags?

**Comment by xfenix** [comment]
Thank you for feedback!

Can you specify more information?
Are you talking about something like this: `<span>something</span> going here` ==> `<span>something</span>going here`?

Hmm. It may be because of https://github.com/xfenix/django-hmin/blob/master/hmin/base.py#L15 bad regular expression, where i lost closing slash exclusion (so it intents to do no harm, suppose to clean spaces after open tags, not closing). I may patch it up with more clever regexp, because it obviously a bug.

**Comment by xfenix** [comment]
Yeap, i found that my fixtures all filled with this behaviour. No doubt — it is bug.

**Comment by dalescher** [comment]
I found a workaround. I hard installed hmin in my django project and commented out the following in base.py:
`# data_input = RE_LEFT_SPACE_AFTER_OPEN_TAG.sub(r"\1", data_input)`
Still have the minification but no more problem with spaces :)

I do not know if it's a good way though.

**Comment by xfenix** [comment]
In those case you get some extra spaces, but it was legit for situation.

Now i fixed this. You can install new 0.5.4 version, it has no this bug. Also i added python 3.9 tests and slightly optimize middleware.
Thanks for bugreport! It helps a lot!

**Comment by xfenix** [comment]
Please, let me know, if you experience another issues or this issue will strike back in other scenarios.

**Comment by dalescher** [comment]
hum, I still have the same issue with the new modifications. I still have to comment out 

`data_input = RE_LEFT_SPACE_AFTER_OPEN_TAG.sub(r"\1", data_input)`

to make it works, am I missing something? I just modified all the following files by copy pasting your new versions:
base.py
middleware.py

**Comment by xfenix** [comment]
It's better to install from pypi.
https://github.com/xfenix/django-hmin/blob/cfea5ebb2c3382ba05fd2af860d2e2d2e421f0f1/hmin/tests/helpers.py#L51 also please check regression test, it checks your case. 
If you still have this issue, please provide example (before/after minifcation). Don't forget to clean caches, it may be because of them.

**Comment by Dheirya** [comment]
I'm still having this issue, and I cleaned the caches. I also tried using the `# data_input = RE_LEFT_SPACE_AFTER_OPEN_TAG.sub(r"\1", data_input)`

Which doesn't work.

**Comment by xfenix** [comment]
Do you have installed version 0.5.4?
If you do, please, provide some examples of wrong behaviour
